# Generated by Django 4.2.2 on 2024-07-03 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('full_name', models.CharField(blank=True, help_text='Введите ФИО клиента.', max_length=50, null=True, verbose_name='Ф.И.О')),
                ('comment', models.CharField(blank=True, help_text='Введите комментарий к клиенту.', max_length=100, null=True, verbose_name='комментарий')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Введите название рассылки.', max_length=50, null=True, verbose_name='Название')),
                ('first_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата первой отправкм')),
                ('date_try', models.DateTimeField(blank=True, null=True, verbose_name='Дата последней попытки')),
                ('periodicity', models.CharField(blank=True, choices=[('one_a_day', 'Ежедневная рассылка'), ('one_a_week', 'Еженедельная рассылка'), ('one_a_month', 'Ежемесячная рассылка')], help_text='Выберите периодичность.', max_length=20, null=True, verbose_name='Периодичность рассылки')),
                ('status', models.CharField(blank=True, choices=[('created', 'Создана'), ('launched', 'Запущена'), ('completed', 'Завершена')], help_text='Выберите статус.', max_length=20, null=True, verbose_name='Cтатус рассылки')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
                'permissions': [('can_change_status', 'Can change status')],
            },
        ),
        migrations.CreateModel(
            name='MailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, help_text='Введите тему письма.', max_length=100, null=True, verbose_name='Тема письма')),
                ('body', models.TextField(blank=True, help_text='Введите текст письма.', null=True, verbose_name='Тело письма')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
            },
        ),
        migrations.CreateModel(
            name='MailTry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата и время последней попытки')),
                ('status', models.CharField(blank=True, choices=[('success', 'Успешно'), ('fail', 'Не успешно')], max_length=20, null=True, verbose_name='Cтатус попытки')),
                ('servers_answer', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ответ сервера')),
                ('mail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mailtry', to='mail.mail', verbose_name='Попытка данной рассылки')),
            ],
            options={
                'verbose_name': 'попытка',
                'verbose_name_plural': 'попытки',
            },
        ),
    ]
