# Generated by Django 4.2.2 on 2024-07-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='first_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата первой отправки'),
        ),
    ]
