# Generated by Django 4.2.2 on 2024-07-02 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_client_owner_mail_owner_mailmessage_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mail',
            options={'permissions': [('can_see_mails', 'can_change_status')], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
        migrations.RenameField(
            model_name='mail',
            old_name='client',
            new_name='clients',
        ),
        migrations.AddField(
            model_name='mail',
            name='date_try',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата последней попытки'),
        ),
        migrations.AddField(
            model_name='mailtry',
            name='mail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mailtry', to='mail.mail', verbose_name='Попытка данной рассылки'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='first_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата первой отправкм'),
        ),
    ]
