# Generated by Django 4.2.2 on 2024-07-02 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_alter_mail_options_rename_client_mail_clients_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mail',
            options={'permissions': [('can_change_status', 'Can change status')], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
    ]
