# Generated by Django 4.2.2 on 2024-07-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0005_alter_mail_first_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='datetime_finish',
            field=models.DateTimeField(auto_now=True, help_text='Введите дату, до которой будет действовать рассылка', null=True, verbose_name='Дата последней отправки'),
        ),
        migrations.AddField(
            model_name='mail',
            name='datetime_send',
            field=models.DateTimeField(auto_now=True, help_text='Введите дату первой отправки сообщения в рассылке', null=True, verbose_name='Дата следующей отправки'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='first_date',
            field=models.DateTimeField(blank=True, help_text='Введите дату первой отправки сообщения в рассылке', null=True, verbose_name='Дата первой отправки'),
        ),
    ]
